### ISSUE TITLE
`core_progress` kwarg not supported anymore?

### ISSUE THREAD

**Issue by gregsadetsky** [dubovikmaster/parallelbar#2]
Hey,

I found about this great lib through [this answer](https://stackoverflow.com/a/70968053) on StackOverflow

Small note/question: that answer, and the README ([here](https://github.com/dubovikmaster/parallelbar/blob/main/README.md?plain=1#L74)) mention/use the `core_progress` kwarg -- but that kwarg doesn't seem to exist anymore, is that possible? (I found this [change](https://github.com/dubovikmaster/parallelbar/commit/3c4bd99317c49813364810d06b2b90669db47ac9#diff-826b8997f6da99b783f69d1b94c2b7a8165cc6d636399d2443ba00ab53e6cf72L181) in the commit history)

If that's the case, 1) I'd be happy to add a note/comment/edit to the StackOverflow answer 2) I'd also suggest updating the README

And, additionally: is there any way to see a per-process progress bar? :-)

Thanks for your great work! Cheers

**Comment by dubovikmaster** [comment]
Hello and thank you very much for your feedback. Yes, you're right, the core_progress setting was experimental and is no longer supported. But you can install version 0.19.0 for example. Perhaps it will work as you expect.

**Comment by gregsadetsky** [comment]
Thank you!
