### ISSUE TITLE
Passing function parameter by name (e.g. as a dict)

### ISSUE THREAD

**Issue by DaminK** [dubovikmaster/parallelbar#6]
I really like the package as it simplifies parallelization of code. However, I could not find a way to pass parameters to the called functions by name (as a dict for example) instead of their order in the passed tuples. This leads to bad code readability and forces you to keep parameters in the same order or changing all calls. Also it forces you to give values to otherwise optional parameters, if you want to set an optional paramter that occurs afterwards.

A workaround would be to pass all parameters as a dict in a single parameter, but this is also bad practice. And leads to worse code readiblity and documentation.

Is there a way to achieve this with the current version or are there plans to implement this functionality?

Anyways, appreciate all the work you did on the package so far!

P.S: Is there a version of the documentation that is not full of animated gifs? It makes me nauseous to read the text in between.

**Comment by dubovikmaster** [comment]
doesn't the `starmap`  function answer your question?
or I don't understand the question correctly
Please provide a code example

Thank you very much for the feedback

**Comment by dubovikmaster** [comment]
You can do it very simply:
```python
def foo(a,b,balancing_weights=None,verbose=False,precomputed_dists=None,metric='sqeuclidean',unbalanced=False,regularization=None) :
    pass

def unpack_params(kwargs: dict):
    return foo(**kwargs)

result = progress_map(unpack_params, [{"a":a,"b":b,"precomputed_dists":node_dists[a,b],"regularization":"entropic"} for a in A for b in B])

````

**Comment by DaminK** [comment]
Thanks, something like this was my suggestion. I think handling this as part of your package would be a good addition as you can easily type check whether a list of tuples or dicts was passed and it would increase usabilty substantially. But if you prefer people to write their own wrapper function for each function they want to call that is also fine.
